baseURL = "https://xn--cz8h19c.ml/"
languageCode = "de-de"
title = "Cheat Sheets"
description = "Lernzettel f√ºr Klassenarbeiten der Berufsschule bei der Ausbildung zum Mediengestalter Digital und Print."

theme = 'fuji'


[params]
  showReadTime = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
  [[menu.link]]
    name = "WebUntis"
    url = "https://mese.webuntis.com/WebUntis/?school=BK-Technik-Siegen#/basic/timetable"
  [[menu.link]]
    name = "Teams"
    url = "https://teams.microsoft.com"
  [[menu.link]]
    name = "SiWiWissen"
    url = "https://siwiwissen.de"
  [[menu.link]]
    name = "BKT"
    url = "https://berufskolleg-technik.de/"
